import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTypescript,
  SiExpress,
  SiNestjs,
  SiSpringboot,
  SiFastapi,
  SiFirebase,
  SiMongodb,
  SiMysql,
  SiMariadb,
  SiRedis,
  SiKubernetes,
  SiRancher,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaVuejs,
  FaJava,
  FaPython,
  FaHtml5,
  FaCss3Alt,
  FaLaravel,
  FaNodeJs,
  FaFlutter,
  FaGitlab,
  FaDocker,
  FaApple,
  FaLinux,
  FaWindows,
} from "react-icons/fa6";
import { TbBrandAdobeXd, TbBrandNuxt } from "react-icons/tb";
import { RiPhpFill, RiReactjsFill } from "react-icons/ri";
import { DiSqllite } from "react-icons/di";
import { GrOracle } from "react-icons/gr";
import { BiLogoPostgresql } from "react-icons/bi";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
  xd: TbBrandAdobeXd,
  vuejs: FaVuejs,
  reactjs: RiReactjsFill,
  nuxtjs: TbBrandNuxt,
  typescript: SiTypescript,
  java: FaJava,
  python: FaPython,
  php: RiPhpFill,
  html: FaHtml5,
  css: FaCss3Alt,
  expressjs: SiExpress,
  nestjs: SiNestjs,
  laravel: FaLaravel,
  springboot: SiSpringboot,
  fastapi: SiFastapi,
  nodejs: FaNodeJs,
  firebase: SiFirebase,
  flutter: FaFlutter,
  sqllite: DiSqllite,
  oracle: GrOracle,
  postgresql: BiLogoPostgresql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  mariadb: SiMariadb,
  redis: SiRedis,
  gitlab: FaGitlab,
  docker: FaDocker,
  kubernetes: SiKubernetes,
  rancher: SiRancher,
  macos: FaApple,
  linux: FaLinux,
  windows: FaWindows,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
